# Generated by Django 3.2 on 2021-04-09 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('sid', models.AutoField(db_column='SID', primary_key=True, serialize=False)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=100, null=True)),
            ],
            options={
                'db_table': 'STICKER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(db_column='UID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=45, null=True)),
                ('domain', models.CharField(blank=True, db_column='DOMAIN', max_length=20, null=True)),
                ('blur', models.CharField(blank=True, db_column='BLUR', max_length=20, null=True)),
                ('pixel', models.CharField(blank=True, db_column='PIXEL', max_length=20, null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
