# Generated by Django 3.2 on 2021-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_faces_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='blur',
            field=models.CharField(blank=True, db_column='BLUR', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pixel',
            field=models.CharField(blank=True, db_column='PIXEL', max_length=20, null=True),
        ),
    ]
