# Generated by Django 3.2 on 2021-04-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
